### ISSUE TITLE
Propose to add to FreeCAD-Addons

### ISSUE THREAD

**Issue by luzpaz** [Mambix/FreeCAD-yaml-workspace#3]
Add this workbench to https://github.com/FreeCAD/FreeCAD-addons

**Comment by Mambix** [comment]
Created PR here: https://github.com/FreeCAD/FreeCAD-addons/pull/66

I also added more text to readme if anyone would like to contribute. 
Created a quick video and put it on youtube to give people a quick idea of what it can do.
