### ISSUE TITLE
Dude, do you even workbench 

### ISSUE THREAD

**Issue by Mambix** [Mambix/FreeCAD-yaml-workspace#5]
!!!

**Comment by luzpaz** [comment]
The FreeCAD Addon Manager has been updated and we now need an SVG logo of each Workbench/Addon icon. Could you kindly let me know if you can do that? If not we can post on the UI/UX freeCAD subforum to see if someone will create one...?

Ref: https://github.com/FreeCAD/FreeCAD-addons/issues/37

**Comment by Mambix** [comment]
not much of a designer myself. I rather see someone does this job properly :)

**Comment by luzpaz** [comment]
Forum thread requesting help with logo: https://forum.freecadweb.org/viewtopic.php?f=34&t=37049

**Comment by luzpaz** [comment]
@Mambix what do you think of this? 
![image](https://user-images.githubusercontent.com/4140247/59545552-dbf26500-8eed-11e9-964f-f59a24aafc74.png)  
(see thread)

**Comment by Mambix** [comment]
@luzpaz perfect

**Comment by Mambix** [comment]
Modified the name to correctly represent FreeCAD plugin
