### ISSUE TITLE
Add support for adding models by URL

### ISSUE THREAD

**Issue by Mambix** [Mambix/FreeCAD-yaml-workspace#7]
This allows you to specify models found on the internet to be imported. They will be cached locally once downloaded, so next time they will be imported from the cache.

**Comment by Mambix** [comment]
This should probably have to be placed in users temp folders specific to OS. To avoid duplication of downloaded models in case more projects use same objects.

- On Unix/Linux: `~/.yaml-workbench`
- On Windows: `C:\Users\<username>\AppData\Local\Temp\yaml-workbench`

In order to track what file came from what URL, I think it would make sense to save them in `<MD5>.stp` format. That way I can quickly check if it exists in cache. Another option is to ave them with original name but break down URL to directory structure. This one might actually be easier because I don't need to worry about files suffix.

**Comment by luzpaz** [comment]
```
~/.config/FreeCAD/Mod/yaml-workbench 
or
 ~/.FreeCAD/Mod/yaml-workbench
```
Actually I think it's the latter.

**Comment by Mambix** [comment]
I don't think there is a point of implementing DL of 3D models since there are practically impossible to find on the internet. Thingiverse/GrabCAD have free models but you need to be logged in to DL them.

So now you can manually DL needed models and add them to `~/.FreeCAD/Mod/yaml-workbench` folder where they will be loaded from and imported if filenames are not found in project defined `stl` folder.

Here is an example of importing mini ITX motherboard and 6 HDD drives to check NAS case fit:
![image](https://user-images.githubusercontent.com/6792150/103276968-7c3dab00-49fa-11eb-8c87-6c54d801c91f.png)
